INSERT INTO CUSTOMER(NAME,ADDRESS,EMAIL_ADDRESS) VALUES('太郎', '東京都新宿区', 'taro@aa.bb.cc')
INSERT INTO CUSTOMER(NAME,ADDRESS,EMAIL_ADDRESS) VALUES('ジロー', '東京都豊島区', 'jiro@aa.bb.cc')
INSERT INTO CUSTOMER(NAME,ADDRESS,EMAIL_ADDRESS) VALUES('三郎', '長野県松本市', 'sabu@aa.bb.cc')
INSERT INTO CUSTOMER(NAME,ADDRESS,EMAIL_ADDRESS) VALUES('四郎', '東京都足立区', 'siro@aa.bb.cc')